### ISSUE TITLE
No replacement when inside a callout

### ISSUE THREAD

**Issue by francojc** [ute/search-replace#1]
I have an issue with search-replace inside of callouts. 

In the `_quarto.yml` I have: 

```yaml
filters:
  - search-replace
search-replace:
  +hello: "Hello world"
```

In a `.qmd` document the replacement works outside of the callout, but not inside.

```quarto

## +hello <!-- returns: "Hello world" -->

::: {.callout}

## +hello <!-- returns: "+hello" -->

...Callout text...

:::
```

Is there a workaround for this issue?
