### ISSUE TITLE
Format specific search-replace

### ISSUE THREAD

**Issue by ute** [ute/search-replace#4]
In https://github.com/ute/search-replace/issues/3, @dropsplash suggested to make search-replace format specific.

I am planning to implement this sooner or later with a reserved sub-keys,  eg.
```yaml
search-replace:
   +quarto: "[Quarto](https://quarto.org)"
   +qurl  : https://quarto.org/docs
   __condition__1:
       _unless-format_: pdf
       +br : <br>
   __condition__2:
       _when-format_: pdf   
       +br: \ \newline
```

Any comments or suggestions? please let me know 

N.b. this is not implemented yet, PR are welcome 😊
